c_compiler: clang
channel_targets: defaults
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clangxx
extend_keys:
- pin_run_as_build
- extend_keys
- ignore_version
- ignore_build_only_deps
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
lua: '5'
numpy: '1.26'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
platform: osx-arm64
python: '3.11'
r_base: '3.5'
target_platform: osx-arm64
